export class courseService {
  getCourses() {
    return [
      {
        image1: 'accessibility development.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'Web Accessibility Development',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'ecommerce.jpg',
        span1: 'Diploma',
        span2: 'Business',
        p1: 'Diploma in E-Commerce Web Development',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#f49b29',
      },
      {
        image1: 'rails.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'Ruby on Rails for Web Application Development',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'HtmlCss.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'Web Development-Advanced CSS3 Selectors and HTML5 Elemrnts-Revised',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'rails crud.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'Ruby on Rails CRUD app Development and TDD',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'intro web accessibility.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'Intro to Web Accessibility',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'accessibility.jpg',
        span1: 'Diploma',
        span2: 'IT',
        p1: 'Diploma in Web Accessibility',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'auditing.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'Web Accessibility Auditing',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'mysql.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'MySql, Java and URL in Web Application',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'app development.jpg',
        span1: 'Diploma',
        span2: 'IT',
        p1: 'Advanced Diploma in Modern Application Development',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'angular.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'Introduction to Angular 2',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'bootstrap.jpg',
        span1: 'Certificate',
        span2: 'IT',
        p1: 'Bootstrap 4-Exploring New Features',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
      {
        image1: 'firestore.jpg',
        span1: 'Diploma',
        span2: 'Business',
        p1: 'Diploma in Firestore Development',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#f49b29',
      },
      {
        image1: 'advance diploma ecommercegrowth.jpg',
        span1: 'Diploma',
        span2: 'Teaching & Academics',
        p1: 'Advanced Diploma in Economic Growth and Development',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#bfd131',
      },
      {
        image1: 'diploma in community Development.jpg',
        span1: 'Diploma',
        span2: 'Teaching & Academics',
        p1: 'Diploma in Community Development-Revised',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#bfd131',
      },
      {
        image1: 'health.jpg',
        span1: 'Certificate',
        span2: 'Teaching & Academics',
        p1: 'Human Health-Human Development and Health',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#bfd131',
      },
      {
        image1: 'economic growth and development.jpg',
        span1: 'Certificate',
        span2: 'Teaching & Academics',
        p1: 'Economic Growth and Development-Other Human Development Issues',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#bfd131',
      },
      {
        image1: 'economic growth.jpg',
        span1: 'Certificate',
        span2: 'Teaching & Academics',
        p1: 'Economic Growth and Development-Inequality and Human Development',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#bfd131',
      },
      {
        image1: 'introcommunityDevelopment.jpg',
        span1: 'Certificate',
        span2: 'Teaching & Academics',
        p1: 'Inclusion of Minorities in Community Development - Revised',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#bfd131',
      },
      {
        image1: 'diplomahtml.jpg',
        span1: 'Diploma',
        span2: 'IT',
        p1: 'Diploma in HTML5, CSS3 and JavaScript - Revised',
        btn1: 'Start Now',
        s1: '#2d3942',
        s2: '#0091c7',
      },
    ];
  }
}
